language: c
sudo: false
git:
  submodules: true
env:
  global:
    - LUAROCKS=3.0.0
    - LUA=5.3
branches:
  only:
    - master
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get install -y libglfw3-dev
script:
  - bash ./scripts/setup_lua.sh
  - bash ./scripts/run-tests.sh
after_success:
  - coveralls -b .. -r .. -i ./src --dump c.report.json
  - luacov-coveralls -j c.report.json -v
notifications:
  email:
    on_success: change
    on_failure: always
