language: c
os:
  - linux
sudo: true
git:
  submodules: true
env:
  global:
    - LUAROCKS=3.0.0
    - LUA=5.3
branches:
  only:
    - master
before_install:
  - sudo apt-get update && sudo apt-get upgrade -y
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
script:
  - ./scripts/setup_dep.sh
  - ./scripts/setup_lua.sh
  - ./scripts/setup_luarocks.sh
  - ./scripts/build.sh
  - ./scripts/run-tests.sh
after_success:
  - coveralls -b .. -r .. -i ./src --dump c.report.json
  - luacov-coveralls -j c.report.json -v
notifications:
  email:
    on_success: change
    on_failure: always
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
